app:
  version: '1.0.0'
  environment: 'development'

api:
  host: '0.0.0.0'
  port: 8000

model:
  path: 'models/production/best_model.joblib'
  threshold: 0.7

logging:
  level: 'INFO'
  file: 'logs/sqli_detector.log'